
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HSR
 */
public class employeeperformance extends javax.swing.JFrame {

    /**
     * Creates new form employeeperformance
     */
    public employeeperformance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        a2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        a3 = new javax.swing.JTextArea();
        empid = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        a1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1045, 570));

        jPanel1.setLayout(null);

        jScrollPane2.setForeground(new java.awt.Color(0, 0, 0));

        a2.setColumns(20);
        a2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        a2.setRows(5);
        jScrollPane2.setViewportView(a2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(530, 70, 490, 210);

        jButton4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Min Sales");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(660, 290, 280, 50);

        jScrollPane3.setForeground(new java.awt.Color(0, 0, 0));

        a3.setColumns(20);
        a3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        a3.setRows(5);
        jScrollPane3.setViewportView(a3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(540, 340, 490, 210);

        empid.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        empid.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(empid);
        empid.setBounds(230, 160, 200, 40);

        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Reset Sales");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(700, 360, 290, 160);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Employee ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 110, 260, 150);

        jButton1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Get Sales");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 260, 190, 70);

        jButton2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 30, 180, 60);

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        a1.setColumns(20);
        a1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        a1.setRows(5);
        jScrollPane1.setViewportView(a1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 350, 490, 180);

        jButton3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Max Sales");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(640, 10, 280, 60);

        jButton6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(260, 40, 160, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        fffunction f=new fffunction();
        ResultSet rs2=null;
        String pc="price";
        String itm="items";
        rs2=f.find(empid.getText());
        try{
            if(rs2.next()){
                a3.setText(rs2.getString("employeeId"));
                a3.append("\n");
                a3.append(rs2.getString("employeeName"));
                a3.append("\nSales: ");a3.append(rs2.getString("sales"));

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }
        public class fffunction{
            Connection conn2=null;
            ResultSet rs2=null;
            PreparedStatement ps2=null;
            public ResultSet find(String s){
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn2=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject","root","harshdeep");
                    String sql="select employeeId,employeeName,sales from employee where sales in(select min(sales) from employee);";
                    ps2= conn2.prepareStatement(sql);

                    rs2=ps2.executeQuery();

                    if(rs2.next()) {
                        String ID2 = rs2.getString("employeeId");
                        a3.setText(ID2);
                        a3.append("\n");
                        String LD2 = rs2.getString("employeeName");
                        a3.append(LD2);
                        a3.append("\nSales: ");
                        String MD2 = rs2.getString("sales");
                        a3.append(MD2);

                    }
                } catch (Exception e ) {
                    JOptionPane.showMessageDialog(null, e);
                }return rs2;

                // TODO add your handling code here:
            }
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ffffunction f=new ffffunction();
        ResultSet rs3=null;
        rs3=f.find(empid.getText());

        try{

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }
        public class ffffunction{
            Connection conn3=null;
            ResultSet rs3=null;
            PreparedStatement ps3=null;
            public ResultSet find(String s){
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn3=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject","root","harshdeep");
                    String sql="update employee set sales=0";
                    ps3= conn3.prepareStatement(sql);

                    ps3.executeUpdate();

                } catch (Exception e ) {
                    JOptionPane.showMessageDialog(null, e);
                }return rs3;
            }
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Function f=new Function();
        ResultSet rs=null;
        String pc="price";
        String itm="items";
        rs=f.find(empid.getText());
        try{
            if(rs.next()){
                a1.setText(rs.getString("sales"));

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }
        public class Function{
            Connection conn=null;
            ResultSet rs=null;
            PreparedStatement ps=null;
            public ResultSet find(String s){
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject","root","harshdeep");
                    String sql="select employeeId,employeeName,sales from employee where employeeId=?";
                    ps= conn.prepareStatement(sql);
                    ps.setString(1,s);
                    rs=ps.executeQuery();

                    if(rs.next()) {
                        String ID = rs.getString("employeeId");
                        a1.setText(ID);
                        a1.append("\n");
                        String LD = rs.getString("employeeName");
                        a1.append(LD);
                        a1.append("\nSales: ");
                        String MD = rs.getString("sales");
                        a1.append(MD);

                    }
                } catch (Exception e ) {
                    JOptionPane.showMessageDialog(null, e);
                }return rs;
            }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new managerpage().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ffunction f=new ffunction();
        ResultSet rs1=null;
        String pc="price";
        String itm="items";
        rs1=f.find(empid.getText());
        try{
            if(rs1.next()){
                a2.setText(rs1.getString("employeeId"));
                a2.append("\n");
                a2.append(rs1.getString("employeeName"));
                a2.append("\nSales: ");a2.append(rs1.getString("Sales"));

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }
        public class ffunction{
            Connection conn1=null;
            ResultSet rs1=null;
            PreparedStatement ps1=null;
            public ResultSet find(String s){
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn1=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject","root","harshdeep");
                    String sql="select employeeId,employeeName,sales from employee where sales in(select max(sales) from employee);";
                    ps1= conn1.prepareStatement(sql);

                    rs1=ps1.executeQuery();

                    if(rs1.next()) {
                        String ID1 = rs1.getString("employeeId");
                        a2.setText(ID1);
                        a2.append("\n");
                        String LD1 = rs1.getString("employeeName");
                        a2.append(LD1);
                        a2.append("\nSales: ");
                        String MD1 = rs1.getString("sales");
                        a2.append(MD1);

                    }
                } catch (Exception e ) {
                    JOptionPane.showMessageDialog(null, e);
                }return rs1;

            }        // TODO add your handling code here:
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
new updatePerformance().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeperformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeperformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeperformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeperformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeperformance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea a1;
    private javax.swing.JTextArea a2;
    private javax.swing.JTextArea a3;
    private javax.swing.JTextField empid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
