/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HSR
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class employeepage extends javax.swing.JFrame {
    
    Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;

    /**
     * Creates new form employeepage
     */
    public employeepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eid = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        irem = new javax.swing.JTextField();
        ineed = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name2 = new javax.swing.JTextField();
        pid = new javax.swing.JTextField();
        mobi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1045, 570));

        jPanel1.setLayout(null);

        eid.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        eid.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(eid);
        eid.setBounds(810, 310, 210, 30);

        price.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        price.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(price);
        price.setBounds(280, 220, 210, 40);

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Address");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(610, 190, 250, 140);

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Item Remaining");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 240, 280, 140);

        add.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(add);
        add.setBounds(810, 240, 210, 30);

        irem.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        irem.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(irem);
        irem.setBounds(280, 290, 210, 40);

        ineed.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        ineed.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(ineed);
        ineed.setBounds(280, 360, 210, 40);

        jButton3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(540, 430, 130, 80);

        jButton2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Sold");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 440, 220, 60);

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(610, 60, 230, 140);

        jButton1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Get Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 160, 250, 40);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Employee's  Area");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(410, -30, 360, 140);

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("EmpID");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(610, 260, 240, 140);

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Mobile Number");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(610, 120, 280, 140);

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Price");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 170, 230, 140);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Product ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 50, 260, 140);

        name2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        name2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(name2);
        name2.setBounds(810, 110, 210, 30);

        pid.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        pid.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(pid);
        pid.setBounds(280, 100, 210, 40);

        mobi.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        mobi.setForeground(new java.awt.Color(0, 0, 0));
        mobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobiActionPerformed(evt);
            }
        });
        jPanel1.add(mobi);
        mobi.setBounds(810, 170, 210, 30);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Quantity Needed");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 310, 290, 140);

        jButton4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(800, 440, 220, 70);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock2.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1030, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ineed.setText("");
        pid.setText("");
        price.setText("");
        irem.setText("");
        name2.setText("");
        mobi.setText("");
        add.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int a=Integer.parseInt(ineed.getText());
        int b=Integer.parseInt(irem.getText());

        if(a>b || a<=0)
        JOptionPane.showMessageDialog(null, "Enter valid Quantity");
        else
        {
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject","root","harshdeep");
                String sql="UPDATE product set stock=stock-? where productId=?";
                PreparedStatement pstmt= conn.prepareStatement(sql);
                pstmt.setInt(1, Integer.parseInt(ineed.getText()));
                pstmt.setString(2,pid.getText());

                pstmt.executeUpdate();

                String sql1="UPDATE employee set sales=sales+? where employeeId=?";
                PreparedStatement pstmt1= conn.prepareStatement(sql1);
                pstmt1.setInt(1, Integer.parseInt(ineed.getText()));
                pstmt1.setString(2,eid.getText());
                pstmt1.executeUpdate();
                JOptionPane.showMessageDialog(null, "Sold");
                conn.close();

            }
            catch(Exception e)
            {

            }
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn2=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject","root","harshdeep");
                String sql2="insert into customer values (?,?,?,?,?,?,?,?)";
                PreparedStatement pstmt2= conn2.prepareStatement(sql2);
                pstmt2.setString(1,name2.getText());
                pstmt2.setString(2,add.getText());
                pstmt2.setInt(3,Integer.parseInt(mobi.getText()));
                pstmt2.setString(4,pid.getText());

                pstmt2.setInt(5,Integer.parseInt(ineed.getText()));
                pstmt2.setInt(6,Integer.parseInt(price.getText()));
                pstmt2.setInt(7,((Integer.parseInt(ineed.getText()))*(Integer.parseInt(price.getText()))));
                pstmt2.setString(8,eid.getText());

                pstmt2.executeUpdate();

                conn.close();

            }
            catch(Exception e)
            {

            }

        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Function f=new Function();
        ResultSet rs=null;
        String pc="price";
        String itm="items";
        rs=f.find(pid.getText());
        try{
            if(rs.next()){
                price.setText(rs.getString("price"));
                irem.setText(rs.getString("items"));
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }
        public class Function{
            Connection conn=null;
            ResultSet rs=null;
            PreparedStatement ps=null;
            public ResultSet find(String s){
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject","root","harshdeep");
                    String sql="select sellingPrice,stock from product where productId=?";
                    ps= conn.prepareStatement(sql);
                    ps.setString(1,s);
                    rs=ps.executeQuery();

                    if(rs.next()) {
                        String ID = rs.getString("sellingPrice");
                        price.setText(ID);
                        String LD = rs.getString("stock");
                        irem.setText(LD);

                    }
                } catch (Exception e ) {
                    JOptionPane.showMessageDialog(null, e);
                }return rs;
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new login().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed



 /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField ineed;
    private javax.swing.JTextField irem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobi;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
