/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HSR
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class employee extends javax.swing.JFrame {

    /**
     * Creates new form employee
     */
    public employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        age = new javax.swing.JTextField();
        loginpassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        loginid = new javax.swing.JTextField();
        empid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        phno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1020, 600));

        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Name");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(580, 190, 190, 70);

        jButton1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(210, 370, 190, 80);

        age.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        age.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(age);
        age.setBounds(810, 260, 170, 30);

        loginpassword.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        loginpassword.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(loginpassword);
        loginpassword.setBounds(310, 270, 170, 40);

        password.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(password);
        password.setBounds(810, 450, 170, 30);

        address.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        address.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(address);
        address.setBounds(810, 310, 170, 30);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Employee Login");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(400, 20, 240, 90);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Employee ID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(590, 380, 220, 90);

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Address");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(580, 280, 200, 90);

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Password");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(130, 250, 210, 90);

        loginid.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        loginid.setForeground(new java.awt.Color(0, 0, 0));
        loginid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginidActionPerformed(evt);
            }
        });
        jPanel2.add(loginid);
        loginid.setBounds(310, 160, 170, 40);

        empid.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        empid.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(empid);
        empid.setBounds(810, 410, 170, 30);

        name.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(name);
        name.setBounds(810, 208, 170, 32);

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(590, 430, 210, 90);

        jButton2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Add Employee");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(680, 490, 260, 50);

        phno.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        phno.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(phno);
        phno.setBounds(810, 360, 170, 30);

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("New Employee");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(650, 100, 230, 90);

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Age");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(580, 230, 180, 90);

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Employee ID");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(120, 140, 220, 90);

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Phone Number");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(590, 330, 230, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock2.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject","root","harshdeep");
            String sql="select * from employee where employeeId=? and password=?";
            PreparedStatement pstmt= conn.prepareStatement(sql);
            pstmt.setString(1, loginid.getText());
            pstmt.setString(2,loginpassword.getText());
            ResultSet rs=pstmt.executeQuery();
            if (rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome"+loginid.getText(),"Successful Login",JOptionPane.PLAIN_MESSAGE );
                new employeepage().setVisible(true);
                this.setVisible(false);
            }
            else
            JOptionPane.showMessageDialog(null, "Invalid Username/Password","UnSuccessful Login",JOptionPane.ERROR_MESSAGE );

            conn.close();

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loginidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject","root","harshdeep");
            String sql="insert into employee values (?,?,?,?,?,?,0)";
            PreparedStatement pstmt= conn.prepareStatement(sql);
            pstmt.setString(1, name.getText());
            pstmt.setInt(2,Integer.parseInt(age.getText()));
            pstmt.setString(3, address.getText());
            pstmt.setInt(4, Integer.parseInt(phno.getText()));
            pstmt.setString(5, empid.getText());
            pstmt.setString(6, password.getText());
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "AddED");
            conn.close();

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField empid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField loginid;
    private javax.swing.JPasswordField loginpassword;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phno;
    // End of variables declaration//GEN-END:variables
}
